resources:
  dataproc:
    config:
      clusterName: "gcp-data-platform"
      projectId: <<PROJECT ID HERE>>
      region: "us-west1"

solids:
  events_dataproc:
    config:
      date: <<DATE HERE>>
      cluster_name: "gcp-data-platform"

  bq_load_events:
    config:
      date: <<DATE HERE>>
      table: "events.events"

  explore_visits_by_hour:
    config:
      table: "aggregations.explore_visits_per_hour"
