resources:
  credentials_vault:
    config:
      environment_variable_names:
        - DARK_SKY_API_KEY
        - POSTGRES_USERNAME
        - POSTGRES_PASSWORD
        - POSTGRES_HOST
        - POSTGRES_DB