resources:
  postgres_db:
    config:
      username:
        env: POSTGRES_USERNAME
      password:
        env: POSTGRES_PASSWORD
      hostname:
        env: POSTGRES_HOST
      db_name:
        env: POSTGRES_DB