solids:
  train_daily_bike_supply_model:
    inputs:
      trip_table_name: trips_staging
      weather_table_name: weather_staging
    solids:
      produce_training_set:
        config:
          memory_length: 1
      produce_weather_dataset:
        solids:
          load_entire_weather_table:
            config:
              subsets:
              - time
      train_lstm_model_and_upload_to_gcs:
        config:
          model_trainig_config:
            num_epochs: 200
          timeseries_train_test_breakpoint: 10
        inputs:
          bucket_name: dagster-scratch-ccdfe1e
      upload_training_set_to_gcs:
        inputs:
          bucket_name: dagster-scratch-ccdfe1e
          file_name: training_data
