apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dagster.fullname" . }}-celery
  labels:
    app: {{ template "dagster.name" . }}
    chart: {{ template "dagster.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  celery.yaml: |
    execution:
      celery:
        broker:  {{ template "dagster.celery.broker_url" . }}
        backend: {{ template "dagster.celery.backend_url" . }}
        config_source:
{{- if .Values.celery.configSource }}
{{ toYaml .Values.celery.configSource | indent 10 }}
{{- end -}}
