apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "dagster.fullname" . }}-postgresql-secret"
  labels:
    app: "{{ template "dagster.name" . }}"
    chart: "{{ template "dagster.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if not (empty .Values.postgresql) }}
  postgresql-password: "{{ .Values.postgresql.postgresqlPassword | b64enc }}"
  {{- end }}